### PR TITLE
Change Docker tag from master to latest

### PR DESCRIPTION
**Pull request by stevenvegt**
Prevent people from using unstable software.

### CODE REVIEW

**Comment by reinkrul** [comment]
Shouldn't it be `stable`?

**Review by reinkrul — COMMENTED** [review]
Shouldn't it be stable?

Edit: nvm...

**Comment by reinkrul** [comment]
What about Demo EHR and Registry Admin? Those are still on "master"

**Comment by stevenvegt** [comment]
> What about Demo EHR and Registry Admin? Those are still on "master"

I dont think those repos have versions.

**Comment by reinkrul** [comment]
They do :-)

**Pull request merged**
